'use strict'; // code generated by pbf v3.2.1

// alarm_area ========================================

var alarm_area = exports.alarm_area = {};

alarm_area.read = function (pbf, end) {
    return pbf.readFields(alarm_area._readField, {user_id: "", id: "", function_num: 0, priority: 0, target_mmsi: 0, lost_signal: false}, end);
};
alarm_area._readField = function (tag, obj, pbf) {
    if (tag === 1) obj.user_id = pbf.readString();
    else if (tag === 2) obj.id = pbf.readString();
    else if (tag === 3) obj.function_num = pbf.readVarint(true);
    else if (tag === 4) obj.priority = pbf.readVarint(true);
    else if (tag === 5) obj.target_mmsi = pbf.readVarint(true);
    else if (tag === 6) obj.lost_signal = pbf.readBoolean();
};
alarm_area.write = function (obj, pbf) {
    if (obj.user_id) pbf.writeStringField(1, obj.user_id);
    if (obj.id) pbf.writeStringField(2, obj.id);
    if (obj.function_num) pbf.writeVarintField(3, obj.function_num);
    if (obj.priority) pbf.writeVarintField(4, obj.priority);
    if (obj.target_mmsi) pbf.writeVarintField(5, obj.target_mmsi);
    if (obj.lost_signal) pbf.writeBooleanField(6, obj.lost_signal);
};

alarm_area.TargetType = {
    "NORMAL": {
        "value": 0,
        "options": {}
    },
    "RADAR": {
        "value": 1,
        "options": {}
    }
};
